name = "dentafile"
compatibility_date = "2024-01-10"
pages_build_output_dir = "dist"

[build]
command = "npm ci && npm run build"
output_dir = "dist"

# Configure routes for SPA
[[routes]]
pattern = "/*"
dest = "/index.html"

# Environment variables (if needed)
[env.production]
NODE_VERSION = "18.17.1"
NODE_ENV = "production"

# Configure caching rules
[site.cache]
pattern = "**/*.{js,css,html,ico,jpg,png,svg,webp,woff,woff2}"
strategy = "bypass_cache"

# Note: Add your environment variables in the Cloudflare Pages dashboard
# under Settings > Environment variables:
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
