name = "dentafile"
compatibility_date = "2024-01-10"

# Build configuration
[build]
command = "npm ci && npm run build"

# Site configuration
[site]
bucket = "./dist"

# Environment variables
[env.production]
NODE_VERSION = "18.17.1"
NODE_ENV = "production"

# Routes for SPA
[[routes]]
pattern = "/*"
zone_name = "dentafile.pages.dev"
custom_domain = false

# Note: Add your environment variables in the Cloudflare Pages dashboard
# under Settings > Environment variables:
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
