name = "dentafile"
type = "javascript"
main = "dist/worker.js"  # Updated to match Workers JavaScript entry point
compatibility_date = "2024-01-10"
account_id = "c325eea60df358f4c0ee2b056e484ec9"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"
