
name = "dentafile"
compatibility_date = "2024-01-10"

[site]
bucket = "./dist"

# Add Cache rules to prevent stale files from being served
[site.cache]
pattern = "**/*.{js,css,html}"
strategy = "bypass_cache"
