name = "dentafile"
compatibility_date = "2024-01-10"
pages_build_output_dir = "dist"

# Cloudflare Pages specific configuration
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[build]
command = "chmod +x build.sh && ./build.sh"
output_dir = "dist"

# Configure routes for SPA
[[routes]]
pattern = "/*"
dest = "/index.html"

# Environment variables (if needed)
[env.production]
NODE_ENV = "production"

# Configure caching rules
[site.cache]
pattern = "**/*.{js,css,html,ico,jpg,png,svg,webp,woff,woff2}"
strategy = "bypass_cache"
